FROM mongo:latest
# Copia os ficheiros para dentro da imagem durante o build
COPY jogos.json /docker-entrypoint-initdb.d/
COPY autores.json /docker-entrypoint-initdb.d/
COPY categorias.json /docker-entrypoint-initdb.d/
COPY import.sh /docker-entrypoint-initdb.d/