services:
  mongodb:
    build:
      context: ./data
      dockerfile: Dockerfile.mongo
    container_name: mongodb_jogos
    networks:
      - jogos-network

  api_dados:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api_dados
    ports:
      - "17000:17000"
    environment:
      MONGO_URL: mongodb://mongodb:27017/jogostabuleiro
      PORT: 17000
    depends_on:
      - mongodb
    networks:
      - jogos-network

networks:
  jogos-network:
    driver: bridge
